services:
  redqueen-web:
    restart: unless-stopped
    depends_on:
      - redqueen-api
    networks:
      - api
      - proxy
    build:
      context: web/
    ports:
      - "80:80"
  redqueen-api:
    restart: unless-stopped
    environment:
      - REDQUEEN_DB_URL
      - REDQUEEN_LOG_DB_URL
      - REDQUEEN_JWT_DISABLED
      - REDQUEEN_JWT_KEYSET_URL
      - REDQUEEN_JWT_AUDIENCE
      - REDQUEEN_JWT_ISSUER
    networks:
      - api
      - mysql
    build:
      context: php-api/
  door-xbee:
    restart: always
    networks:
      - mysql
    build:
      context: door-xbee/
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
  door-mqtt:
    restart: always
    networks:
      - mysql
      - mqtt
    build:
      context: door-mqtt/
    environment:
      - REDQUEEN_DATABASE=redqueen
      - REDQUEEN_DB_HOST=mysql
      - REDQUEEN_DB_USER=redqueen
      - REDQUEEN_DB_PASS=redqueen
      - REDQUEEN_MQTT_HOST=mosquitto
  mosquitto:
    restart: always
    image: eclipse-mosquitto
    networks:
      - mqtt
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    ports:
      - 1883:1883
  mysql:
    restart: always
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # needed to support door-xbee until it is updated or removed
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=redqueen
      - MYSQL_USER=redqueen
      - MYSQL_PASSWORD=redqueen

volumes:
  mysql_data:

networks:
  api:
  proxy:
  mqtt:
  mysql:
