services:
  redqueen-web:
    image: mlehner/foundry:redqueen-web
    restart: unless-stopped
    depends_on:
      - redqueen-api
    logging: &default-logging
      driver: local
      options:
        max-size: 10m
        max-file: 2
    networks:
      - api
      - proxy
    build:
      context: web/
    ports:
      - "80:80"
    develop:
      watch:
        - action: sync
          path: ../redqueen-js-app/web
          target: /redqueen/web
  redqueen-api:
    image: mlehner/foundry:redqueen-api
    logging: *default-logging
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - REDQUEEN_DB_URL=mysql://${REDQUEEN_DB_USER}:${REDQUEEN_DB_PASS}@mysql/${REDQUEEN_DATABASE}?charset=utf8
      - REDQUEEN_LOG_DB_URL=mysql://${REDQUEEN_DB_USER}:${REDQUEEN_DB_PASS}@mysql/${REDQUEEN_DATABASE}?charset=utf8
      - REDQUEEN_JWT_DISABLED
      - REDQUEEN_JWT_KEYSET_URL
      - REDQUEEN_JWT_AUDIENCE
      - REDQUEEN_JWT_ISSUER
    networks:
      - api
      - mysql
    build:
      context: php-api/
    develop:
      watch:
        - action: sync
          path: ../redqueen-php-api
          target: /redqueen
  door-xbee:
    image: mlehner/foundry:door-xbee
    logging: *default-logging
    profiles: ["xbee"]
    restart: always
    depends_on:
      - mysql
    networks:
      - mysql
    build:
      context: door/
      target: door-xbee
    environment:
      - REDQUEEN_DB_HOST=mysql
      - REDQUEEN_XBEE_DOOR_IDENTIFIER
      - REDQUEEN_DATABASE
      - REDQUEEN_DB_USER
      - REDQUEEN_DB_PASS
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
  door-mqtt:
    image: mlehner/foundry:door-mqtt
    logging: *default-logging
    restart: always
    depends_on:
      - mysql
    networks:
      - mysql
      - mqtt
    build:
      context: door/
      target: door-mqtt
    environment:
      - REDQUEEN_DB_HOST=mysql
      - REDQUEEN_MQTT_HOST=mosquitto
      - REDQUEEN_DATABASE
      - REDQUEEN_DB_USER
      - REDQUEEN_DB_PASS
  mosquitto:
    restart: always
    logging: *default-logging
    image: eclipse-mosquitto
    networks:
      - mqtt
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    ports:
      - 1883:1883
  mysql:
    restart: always
    logging: *default-logging
    image: mysql
    command:
      - --performance-schema=OFF
    networks:
      - mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE="$REDQUEEN_DATABASE"
      - MYSQL_USER="$REDQUEEN_DB_USER"
      - MYSQL_PASSWORD="$REDQUEEN_DB_PASS"

volumes:
  mysql_data:

networks:
  api:
  proxy:
  mqtt:
  mysql:
