version: '3'
services:
  redqueen-web:
    networks:
      - redqueen
    build:
      context: web/
    ports:
      - 80
  redqueen-api:
    environment:
      REDQUEEN_DB_URL: mysql://redqueen:redqueen@mysql:3306/redqueen?charset=utf8
    networks:
      - redqueen
      - mysql
    build:
      context: php-api/
  redqueen-serial:
    networks:
      - mysql
    build:
      context: serial/

networks:
  redqueen:
  mysql:
    external: true
