version: '3'
services:
  redqueen-web:
    restart: unless-stopped
    depends_on:
      - redqueen-api
    networks:
      - api
      - proxy
    build:
      context: web/
    ports:
      - "80:80"
  redqueen-api:
    restart: unless-stopped
    environment:
      - REDQUEEN_DB_URL
      - REDQUEEN_LOG_DB_URL
      - REDQUEEN_JWT_DISABLED
      - REDQUEEN_JWT_KEYSET_URL
      - REDQUEEN_JWT_AUDIENCE
      - REDQUEEN_JWT_ISSUER
    networks:
      - api
      - mysql
    build:
      context: php-api/
  redqueen-serial:
    restart: always
    networks:
      - mysql
    build:
      context: serial/
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

networks:
  api:
  proxy:
  mysql:
    external: true
